# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_tests_result_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Test Name'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='result_type',
            field=models.CharField(choices=[('NUM', 'NUMERIC'), ('ALF', 'ALFANUMERIC'), ('TXT', 'TEXT'), ('IMG', 'IMAGE')], default='NUM', max_length=3, verbose_name='Result Type'),
        ),
    ]
