# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20180428_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Test Name'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='parent',
            field=models.IntegerField(blank=True, help_text='Parent', null=True, verbose_name='Parent'),
        ),
    ]
