# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 11:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20180428_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='billing.Tests'),
        ),
    ]
