# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20180428_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='parent',
            field=models.IntegerField(blank=True, help_text='Parent', null=True, verbose_name='Parent'),
        ),
    ]
