# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20180428_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='billing.Tests'),
        ),
    ]
