# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0011_auto_20180428_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(help_text='Patient Name', max_length=100, verbose_name='Name')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_order', to='billing.Orders', verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'sample_id'],
                'verbose_name': 'Order samples',
                'verbose_name_plural': 'Order samples',
                'permissions': (('view_ordersamples', 'Can view order samples'),),
            },
        ),
        migrations.CreateModel(
            name='Specimens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Specimen Name')),
                ('suffix_code', models.CharField(max_length=3, verbose_name='Suffix code')),
            ],
            options={
                'verbose_name': 'Specimen',
                'verbose_name_plural': 'Specimens',
            },
        ),
        migrations.AddField(
            model_name='ordersamples',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_specimen', to='billing.Specimens', verbose_name='Specimen'),
        ),
        migrations.AddField(
            model_name='tests',
            name='specimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_specimen', to='billing.Specimens', verbose_name='Specimen'),
        ),
    ]
