# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20180506_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersamples',
            options={'ordering': ['order', 'sample_no'], 'permissions': (('view_ordersamples', 'Can view order samples'),), 'verbose_name': 'Order samples', 'verbose_name_plural': 'Order samples'},
        ),
        migrations.RenameField(
            model_name='ordersamples',
            old_name='sample_id',
            new_name='sample_no',
        ),
    ]
