# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20180506_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.Diagnosis', verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.Insurance', verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.Priority', verbose_name='Order priority'),
        ),
    ]
