# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_supergroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_order', to='billing.Orders', verbose_name='Order')),
                ('supergroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_supergrup', to='billing.SuperGroups', verbose_name='Super Group')),
            ],
        ),
        migrations.CreateModel(
            name='Specimens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Tubes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('suffix', models.CharField(max_length=100, verbose_name='Suffix')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tube_specimen', to='middleware.Specimens', verbose_name='Specimen')),
            ],
        ),
        migrations.AddField(
            model_name='receivedsamples',
            name='tube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_tube', to='middleware.Tubes', verbose_name='Specimen'),
        ),
    ]
