# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180415_2235'),
        ('middleware', '0002_auto_20180415_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='order',
        ),
        migrations.RemoveField(
            model_name='results',
            name='test',
        ),
        migrations.AddField(
            model_name='results',
            name='order_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_test', to='billing.OrderTests', verbose_name='Order test'),
            preserve_default=False,
        ),
    ]
