# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20180428_1836'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('middleware', '0004_auto_20180423_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParameters',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='billing.Tests')),
                ('method', models.CharField(max_length=100, null=True, verbose_name='Method')),
                ('unit', models.CharField(max_length=100, null=True, verbose_name='Test unit')),
                ('decimal', models.IntegerField(null=True, verbose_name='Decimal place')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
        ),
        migrations.CreateModel(
            name='TestRefRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField(null=True, verbose_name='Age from')),
                ('age_to', models.IntegerField(null=True, verbose_name='Age to')),
                ('age_type', models.CharField(choices=[('D', 'DAY'), ('M', 'MONTH'), ('Y', 'YEAR')], max_length=3, null=True, verbose_name='Age to unit')),
                ('any_age', models.BooleanField(default=True, verbose_name='Any age?')),
                ('lower', models.IntegerField(null=True, verbose_name='lower limit')),
                ('upper', models.IntegerField(null=True, verbose_name='upper limit')),
                ('operator', models.IntegerField(null=True, verbose_name='operator value')),
                ('alfa_value', models.CharField(max_length=100, null=True, verbose_name='Alfanumberic value')),
                ('special_info', models.TextField(null=True, verbose_name='Special information')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refranges_gender', to='billing.Genders', verbose_name='Gender')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refranges_test', to='billing.Tests', verbose_name='Test')),
            ],
        ),
        migrations.AddField(
            model_name='orderresults',
            name='is_header',
            field=models.BooleanField(default=False, verbose_name='is header?'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='patologi_mark',
            field=models.CharField(max_length=2, null=True, verbose_name='Patologi mark'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='ref_range',
            field=models.CharField(max_length=200, null=True, verbose_name='Reference range'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='unit',
            field=models.CharField(max_length=100, null=True, verbose_name='Result unit'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='validation_status',
            field=models.IntegerField(default=0, verbose_name='Validation status'),
        ),
    ]
