# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0006_auto_20180428_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrefranges',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refranges_gender', to='billing.Genders', verbose_name='Gender'),
        ),
    ]
