# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20180506_1127'),
        ('middleware', '0007_auto_20180428_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimens',
            name='lastmodifiedby',
        ),
        migrations.RemoveField(
            model_name='tubes',
            name='lastmodifiedby',
        ),
        migrations.RemoveField(
            model_name='tubes',
            name='specimen',
        ),
        migrations.RemoveField(
            model_name='receivedsamples',
            name='tube',
        ),
        migrations.AddField(
            model_name='receivedsamples',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_tube', to='billing.OrderSamples', verbose_name='Specimen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='ref_range',
            field=models.CharField(max_length=100, null=True, verbose_name='Reference range'),
        ),
        migrations.DeleteModel(
            name='Specimens',
        ),
        migrations.DeleteModel(
            name='Tubes',
        ),
    ]
