# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0008_auto_20180506_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrefranges',
            name='operator_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='operator value'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='operator',
            field=models.CharField(blank=True, choices=[('-', 'NA'), ('>', 'GT'), ('>=', 'GTE'), ('<', 'LT'), ('<=', 'LTE')], max_length=3, null=True, verbose_name='Operator'),
        ),
    ]
