# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0010_results_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresults',
            name='print_status',
            field=models.IntegerField(default=0, verbose_name='Print status'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='print_user',
            field=models.CharField(max_length=2, null=True, verbose_name='Print by'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='validation_user',
            field=models.CharField(max_length=2, null=True, verbose_name='Validated by'),
        ),
    ]
