# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0011_auto_20180510_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresults',
            name='print_date',
            field=models.DateTimeField(null=True, verbose_name='Print date'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='validation_date',
            field=models.DateTimeField(null=True, verbose_name='Validated date'),
        ),
    ]
