# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0012_auto_20180510_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderresults',
            name='print_user',
            field=models.CharField(max_length=20, null=True, verbose_name='Print by'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='validation_user',
            field=models.CharField(max_length=20, null=True, verbose_name='Validated by'),
        ),
    ]
