# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0014_auto_20180524_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
