# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0015_auto_20180524_2055'),
        ('middleware', '0016_results_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=20, null=True, verbose_name='Action code')),
                ('action_user', models.CharField(max_length=20, null=True, verbose_name='Action by')),
                ('action_date', models.DateTimeField(null=True, verbose_name='Action date')),
                ('action_text', models.CharField(max_length=20, null=True, verbose_name='Action text')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historyorder_order', to='billing.Orders', verbose_name='Order')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historyorder_test', to='billing.Tests', verbose_name='Test')),
            ],
        ),
        migrations.AddField(
            model_name='instrumentflags',
            name='flag_mark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Host flag mark'),
        ),
    ]
