# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0017_auto_20180602_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorders',
            name='action_text',
            field=models.CharField(max_length=1000, null=True, verbose_name='Action text'),
        ),
    ]
