# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0018_auto_20180602_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderresults',
            name='patologi_mark',
            field=models.CharField(max_length=20, null=True, verbose_name='Patologi mark'),
        ),
    ]
