# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0015_auto_20180524_2055'),
        ('middleware', '0019_auto_20180602_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtended',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='billing.Orders')),
                ('result_pdf_url', models.CharField(max_length=500, null=True, verbose_name='Result PDF url')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
        ),
    ]
