# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0020_orderextended'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameters',
            name='special_information',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Special information'),
        ),
    ]
